/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Leo Family
 */

public class Temporizador extends javax.swing.JFrame implements Runnable {

      Thread h1;
      String activado = "si";
    
      int i = 0;
      
      Taqillas_activas ta = new Taqillas_activas();
      Despegue des = new Despegue();
      Vista_main vm = new Vista_main();
      Estadisticas_taquillas et =new Estadisticas_taquillas();
      Estadisticas_despegues ed = new Estadisticas_despegues();
      
      int opcion;
    
    public Temporizador(String seg, int opcion) {  
        this.setTitle("Temporizador");
        
        i=Integer.parseInt(seg);
        
        this.opcion = opcion;
        
        if (i==0 || i<0 || i>200){
        
            JOptionPane.showMessageDialog(null," Coloca un tiempo de ejecucion valido.","Error",JOptionPane.ERROR_MESSAGE);
            h1.suspend();
            dispose();
            
        }
        
        if(opcion ==1){
  
              ta.setVisible(true);
        }else{
              des.setVisible(true);
              
        }
   
        initComponents();
        h1 = new Thread(this);
        
        //setLocationRelativeTo(null);
                                 
        run();
        h1.start();
       
    }
    
       
     
     public void run() {

        Thread ct = Thread.currentThread();
        while (ct == h1) {
            
            i = i - 1;
 
            if(i<=9){
                time.setText("0:0" + i);
            }else{
            time.setText("0:" + i);
            }
            
            // para color de cuadro
            if (i == 21) {
                time.setBackground(Color.orange);
            }
            if (i == 10) {
                time.setBackground(Color.red);
            }
            if (i == 0 && opcion==0) {
                //ta.dispose();
                des.dispose();
                    
                //h1.suspend();
                this.dispose();
                vm.setVisible(true);
                ed.setVisible(true);
            }
            
            if (i == 0 && opcion ==1) {
                ta.dispose();
                //des.dispose();
             
                //h1.suspend();
                this.dispose();
                vm.setVisible(true);
                et.setVisible(true);
            }
            
            if(i>60){
                
                time.setText("" + i);
                
            }
            
            
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
    }

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        time = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(800, 700));

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_main/temporizador.jpg"))); // NOI18N

        time.setBackground(new java.awt.Color(255, 255, 255));
        time.setFont(new java.awt.Font("Dialog", 0, 60)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setText("0:00");

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
