/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Leo Family
 */
public class Vista_main extends javax.swing.JFrame {
    
    public int t_vuelos;
    
    
    
    public void Guardar_tiempo_v(){
    
    
    
    t_vuelos=Integer.parseInt(Tiempo_despegue.getText());
    System.out.println(t_vuelos);
    
}
    
    public int getTiempo_despegue() {
        return t_vuelos;        
    }

    /**
     * Creates new form Vista_main
     */
    public int getTiempo_taquillas() {  
        
        int tiempo= Integer.parseInt(Tiempo_taquillas.getText());
        return tiempo;
    }

    public Vista_main() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setTitle("Simulacion de Aereopuerto Manuel Piar");
        
        Tiempo_taquillas.setText("0");
        Tiempo_despegue.setText("0");
     
        
        setIcon();
        //System.out.print();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jButton1 = new javax.swing.JButton();
        Boton_Despegue = new javax.swing.JButton();
        Boton_taquillas = new javax.swing.JButton();
        Boton_extras = new javax.swing.JButton();
        Tiempo_taquillas = new javax.swing.JTextField();
        Tiempo_despegue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_main/Vista arriba Main.jpg"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/boton_salir_pequeño 1.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/boton_salir_pequeño 3.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/boton_salir_pequeño 2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Boton_Despegue.setContentAreaFilled(false);
        Boton_Despegue.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Boton_despegue 2.png"))); // NOI18N
        Boton_Despegue.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Boton_despegue 1.png"))); // NOI18N
        Boton_Despegue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_DespegueActionPerformed(evt);
            }
        });

        Boton_taquillas.setContentAreaFilled(false);
        Boton_taquillas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/boton taquilla 2.png"))); // NOI18N
        Boton_taquillas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/boton taquilla 1.png"))); // NOI18N
        Boton_taquillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_taquillasActionPerformed(evt);
            }
        });

        Boton_extras.setContentAreaFilled(false);
        Boton_extras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/boton extras 2.png"))); // NOI18N
        Boton_extras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/boton extras 1.png"))); // NOI18N
        Boton_extras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_extrasActionPerformed(evt);
            }
        });

        Tiempo_taquillas.setBackground(new java.awt.Color(104, 80, 16));
        Tiempo_taquillas.setMinimumSize(new java.awt.Dimension(24, 19));
        Tiempo_taquillas.setPreferredSize(new java.awt.Dimension(4, 19));
        Tiempo_taquillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tiempo_taquillasActionPerformed(evt);
            }
        });

        Tiempo_despegue.setBackground(new java.awt.Color(101, 78, 15));
        Tiempo_despegue.setMinimumSize(new java.awt.Dimension(24, 19));
        Tiempo_despegue.setPreferredSize(new java.awt.Dimension(4, 19));

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tiempo_taquillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tiempo_despegue, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Boton_Despegue, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(Boton_extras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Boton_taquillas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Boton_Despegue, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Boton_extras, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(Boton_taquillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                        .addComponent(Tiempo_taquillas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tiempo_despegue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Main_Portada mp = new Main_Portada();
        
        mp.setVisible(true);
        
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Boton_taquillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_taquillasActionPerformed

        /*
        if((Tiempo_taquillas.getText())==a){            
            JOptionPane.showMessageDialog(null," Coloca un tiempo de ejecucion");     
        }
        */
    try{
        
        Genera_taquillas gt =new Genera_taquillas();
        gt.retornatiempo(Tiempo_taquillas.getText());
        Temporizador T = new Temporizador(Tiempo_taquillas.getText(),1);
        T.setVisible(true);
        
        this.setVisible(false);
        
    }catch(Exception e){
        
    System.out.println("hola");
    }
                
    }//GEN-LAST:event_Boton_taquillasActionPerformed

    private void Tiempo_taquillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tiempo_taquillasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tiempo_taquillasActionPerformed

    private void Boton_extrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_extrasActionPerformed
        
    }//GEN-LAST:event_Boton_extrasActionPerformed

    private void Boton_DespegueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_DespegueActionPerformed
        
        
        
        try{
        
        Genera_vuelos gv =new Genera_vuelos();
        gv.retornatiempo(Tiempo_despegue.getText());
        Temporizador TA = new Temporizador(Tiempo_despegue.getText(),0);
        TA.setVisible(true); 
        
        this.setVisible(false);
        }catch(Exception e){
            
            
        }
        
    }//GEN-LAST:event_Boton_DespegueActionPerformed

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes_main/logo.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Despegue;
    private javax.swing.JButton Boton_extras;
    private javax.swing.JButton Boton_taquillas;
    private javax.swing.JTextField Tiempo_despegue;
    private javax.swing.JTextField Tiempo_taquillas;
    private javax.swing.JButton jButton1;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    // End of variables declaration//GEN-END:variables

}
